package scaffold

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	templateassets "github.com/averyfreeman/adr-repo-governance/docs/templates"
	"gopkg.in/yaml.v3"
)

const (
	defaultDirectory = "."
	configFilename   = ".adr-scaffold.yaml"
)

// Config controls one scaffold operation.
type Config struct {
	Language string
	Dir      string
	Force    bool
	Output   io.Writer
	Input    io.Reader
	Resolve  Resolver
}

// Result describes files generated by a scaffold operation.
type Result struct {
	Language  string   `json:"language"`
	Directory string   `json:"directory"`
	Files     []string `json:"files"`
	Config    string   `json:"config"`
}

// Resolver chooses what to do when a generated file already exists.
type Resolver func(path string, input io.Reader, output io.Writer) (Action, string, error)

// Action is the resolution for a generated-file collision.
type Action int

const (
	ActionOverwrite Action = iota
	ActionSkip
	ActionRename
	ActionAlternate
)

type catalog struct {
	Version   int                       `yaml:"version"`
	Git       gitDefaults               `yaml:"git"`
	Languages map[string]languageConfig `yaml:"languages"`
}

type gitDefaults struct {
	Branch       string `yaml:"branch"`
	Versioning   string `yaml:"versioning"`
	InitialTag   string `yaml:"initial_tag"`
	CommitStyle  string `yaml:"commit_style"`
	Init         bool   `yaml:"init"`
	Commit       bool   `yaml:"commit"`
	Tag          bool   `yaml:"tag"`
	Push         bool   `yaml:"push"`
	CreateRemote bool   `yaml:"create_remote"`
}

type languageConfig struct {
	DisplayName      string   `yaml:"display_name"`
	Aliases          []string `yaml:"aliases"`
	Template         string   `yaml:"template"`
	SourceExtensions []string `yaml:"source_extensions"`
	Build            string   `yaml:"build"`
	Test             string   `yaml:"test"`
	Format           string   `yaml:"format"`
	Documentation    string   `yaml:"documentation"`
	IgnorePatterns   []string `yaml:"ignore_patterns"`
}

type templateData struct {
	Language         string
	DisplayName      string
	BuildCommand     string
	TestCommand      string
	FormatCommand    string
	Documentation    string
	IgnorePatterns   []string
	SourceExtensions []string
}

type generatedFile struct {
	RelativePath string
	Content      []byte
}

type projectConfig struct {
	Version  int        `yaml:"version"`
	Language string     `yaml:"language"`
	Git      projectGit `yaml:"git"`
}

type projectGit struct {
	Branch       string `yaml:"branch"`
	Versioning   string `yaml:"versioning"`
	InitialTag   string `yaml:"initial_tag"`
	CommitStyle  string `yaml:"commit_style"`
	Init         bool   `yaml:"init"`
	Commit       bool   `yaml:"commit"`
	Tag          bool   `yaml:"tag"`
	Push         bool   `yaml:"push"`
	CreateRemote bool   `yaml:"create_remote"`
}

var (
	catalogData catalog
	catalogErr  error
)

func init() {
	data, err := templateassets.FS.ReadFile("catalog.yaml")
	if err != nil {
		catalogErr = fmt.Errorf("read scaffold catalog: %w", err)
		return
	}
	if err := yaml.Unmarshal(data, &catalogData); err != nil {
		catalogErr = fmt.Errorf("parse scaffold catalog: %w", err)
	}
}

// Languages returns the canonical scaffold language names in stable order.
func Languages() []string {
	if catalogErr != nil {
		return nil
	}
	languages := make([]string, 0, len(catalogData.Languages))
	for language := range catalogData.Languages {
		languages = append(languages, language)
	}
	sort.Strings(languages)
	return languages
}

// Run generates a language scaffold without performing Git or network actions.
func Run(cfg *Config) (*Result, error) {
	if cfg == nil {
		return nil, errors.New("scaffold configuration is required")
	}
	language, profile, err := resolveLanguage(cfg.Language)
	if err != nil {
		return nil, err
	}
	dir := cfg.Dir
	if dir == "" {
		dir = defaultDirectory
	}
	output := cfg.Output
	if output == nil {
		output = os.Stdout
	}
	input := cfg.Input
	if input == nil {
		input = os.Stdin
	}

	data := templateData{
		Language:         language,
		DisplayName:      profile.DisplayName,
		BuildCommand:     nonEmpty(profile.Build, "not defined"),
		TestCommand:      nonEmpty(profile.Test, "not defined"),
		FormatCommand:    nonEmpty(profile.Format, "not defined"),
		Documentation:    profile.Documentation,
		IgnorePatterns:   profile.IgnorePatterns,
		SourceExtensions: profile.SourceExtensions,
	}

	files, err := renderFiles(profile.Template, data)
	if err != nil {
		return nil, err
	}
	configContent, err := renderProjectConfig(language)
	if err != nil {
		return nil, err
	}
	files = append(files, generatedFile{RelativePath: configFilename, Content: configContent})

	planned, err := resolveCollisions(dir, files, cfg.Force, cfg.Resolve, input, output)
	if err != nil {
		return nil, err
	}
	result := &Result{
		Language:  language,
		Directory: dir,
		Files:     make([]string, 0, len(planned)),
		Config:    filepath.ToSlash(filepath.Join(dir, configFilename)),
	}
	for _, file := range planned {
		target := filepath.Join(dir, filepath.FromSlash(file.RelativePath))
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			return nil, fmt.Errorf("create scaffold directory for %s: %w", file.RelativePath, err)
		}
		if err := os.WriteFile(target, file.Content, 0644); err != nil {
			return nil, fmt.Errorf("write scaffold file %s: %w", target, err)
		}
		result.Files = append(result.Files, filepath.ToSlash(filepath.Join(dir, file.RelativePath)))
	}
	sort.Strings(result.Files)
	return result, nil
}

func resolveLanguage(name string) (string, languageConfig, error) {
	if catalogErr != nil {
		return "", languageConfig{}, catalogErr
	}
	needle := strings.ToLower(strings.TrimSpace(name))
	if needle == "" {
		return "", languageConfig{}, fmt.Errorf("language is required; choose one of: %s", strings.Join(Languages(), ", "))
	}
	for language, profile := range catalogData.Languages {
		if needle == language || containsFold(profile.Aliases, needle) {
			return language, profile, nil
		}
	}
	return "", languageConfig{}, fmt.Errorf("unknown language %q; choose one of: %s", name, strings.Join(Languages(), ", "))
}

func renderFiles(templateName string, data templateData) ([]generatedFile, error) {
	files := []struct {
		source string
		output string
	}{
		{source: "AGENTS.md", output: "AGENTS.md"},
		{source: "CLAUDE.md", output: "CLAUDE.md"},
		{source: "repo-init_SKILL.md", output: ".agents/skills/repo-init/SKILL.md"},
		{source: "language-generation_SKILL.md", output: ".agents/skills/language-generation/SKILL.md"},
		{source: "starlight-doc-deployment_SKILL.md", output: ".agents/skills/starlight-doc-deployment/SKILL.md"},
		{source: "version-tag-and-commit-standards_SKILL.md", output: ".agents/skills/version-tag-and-commit-standards/SKILL.md"},
		{source: "gitignore", output: ".gitignore"},
		{source: "README.md", output: "README.md"},
	}
	result := make([]generatedFile, 0, len(files))
	for _, file := range files {
		candidates := []string{file.source}
		if templateName == "rust" && file.source == "language-generation_SKILL.md" {
			candidates = append([]string{"rustdoc-generation_SKILL.md"}, candidates...)
		}
		var content []byte
		var assetPath string
		for _, candidate := range candidates {
			assetPath = path.Join(templateName, candidate)
			content, _ = templateassets.FS.ReadFile(assetPath)
			if content != nil {
				break
			}
			assetPath = path.Join("generic", candidate)
			content, _ = templateassets.FS.ReadFile(assetPath)
			if content != nil {
				break
			}
		}
		if content == nil {
			return nil, fmt.Errorf("read scaffold template %s", assetPath)
		}
		rendered, err := template.New(file.source).Option("missingkey=error").Parse(string(content))
		if err != nil {
			return nil, fmt.Errorf("parse scaffold template %s: %w", assetPath, err)
		}
		var buffer strings.Builder
		if err := rendered.Execute(&buffer, data); err != nil {
			return nil, fmt.Errorf("render scaffold template %s: %w", assetPath, err)
		}
		result = append(result, generatedFile{RelativePath: file.output, Content: []byte(buffer.String())})
	}
	return result, nil
}

func renderProjectConfig(language string) ([]byte, error) {
	config := projectConfig{
		Version:  catalogData.Version,
		Language: language,
		Git: projectGit{
			Branch:       catalogData.Git.Branch,
			Versioning:   catalogData.Git.Versioning,
			InitialTag:   catalogData.Git.InitialTag,
			CommitStyle:  catalogData.Git.CommitStyle,
			Init:         catalogData.Git.Init,
			Commit:       catalogData.Git.Commit,
			Tag:          catalogData.Git.Tag,
			Push:         catalogData.Git.Push,
			CreateRemote: catalogData.Git.CreateRemote,
		},
	}
	data, err := yaml.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("encode scaffold config: %w", err)
	}
	return data, nil
}

func resolveCollisions(dir string, files []generatedFile, force bool, resolver Resolver, input io.Reader, output io.Writer) ([]generatedFile, error) {
	planned := make([]generatedFile, 0, len(files))
	seen := make(map[string]struct{}, len(files))
	for _, file := range files {
		relativePath, err := safeRelativePath(file.RelativePath)
		if err != nil {
			return nil, err
		}
		if _, exists := seen[relativePath]; exists {
			return nil, fmt.Errorf("duplicate scaffold output path %s", relativePath)
		}
		seen[relativePath] = struct{}{}
		file.RelativePath = relativePath
		target := filepath.Join(dir, filepath.FromSlash(relativePath))
		if _, err := os.Stat(target); err != nil {
			if os.IsNotExist(err) {
				planned = append(planned, file)
				continue
			}
			return nil, fmt.Errorf("check scaffold file %s: %w", target, err)
		}
		if force {
			planned = append(planned, file)
			continue
		}
		if resolver == nil {
			if !isTerminal(input) {
				return nil, fmt.Errorf("scaffold file already exists: %s; rerun with --force or use an interactive terminal", target)
			}
			input = bufio.NewReader(input)
			resolver = promptResolver
		}
		action, alternate, err := resolver(relativePath, input, output)
		if err != nil {
			return nil, err
		}
		switch action {
		case ActionOverwrite:
			planned = append(planned, file)
		case ActionSkip:
			continue
		case ActionRename:
			newPath, err := nextAvailableName(dir, relativePath)
			if err != nil {
				return nil, err
			}
			file.RelativePath = newPath
			seen[newPath] = struct{}{}
			planned = append(planned, file)
		case ActionAlternate:
			newPath, err := safeRelativePath(alternate)
			if err != nil {
				return nil, err
			}
			if _, exists := seen[newPath]; exists {
				return nil, fmt.Errorf("alternate scaffold filename already planned: %s", newPath)
			}
			if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(newPath))); err == nil {
				return nil, fmt.Errorf("alternate scaffold filename already exists: %s", newPath)
			} else if !os.IsNotExist(err) {
				return nil, fmt.Errorf("check alternate scaffold filename %s: %w", newPath, err)
			}
			file.RelativePath = newPath
			seen[newPath] = struct{}{}
			planned = append(planned, file)
		default:
			return nil, fmt.Errorf("unknown scaffold collision action %d", action)
		}
	}
	return planned, nil
}

func promptResolver(path string, input io.Reader, output io.Writer) (Action, string, error) {
	reader, ok := input.(*bufio.Reader)
	if !ok {
		reader = bufio.NewReader(input)
	}
	for {
		if _, err := fmt.Fprintf(output, "File %s exists: [o]verwrite, [s]kip, [r]ename, [a]lternate path? ", path); err != nil {
			return 0, "", err
		}
		answer, err := reader.ReadString('\n')
		if err != nil && !errors.Is(err, io.EOF) {
			return 0, "", fmt.Errorf("read collision choice: %w", err)
		}
		choice := strings.ToLower(strings.TrimSpace(answer))
		switch choice {
		case "o", "overwrite":
			return ActionOverwrite, "", nil
		case "s", "skip":
			return ActionSkip, "", nil
		case "r", "rename":
			return ActionRename, "", nil
		case "a", "alternate":
			if _, err := fmt.Fprint(output, "Enter the replacement filename: "); err != nil {
				return 0, "", err
			}
			alternate, readErr := reader.ReadString('\n')
			if readErr != nil && !errors.Is(readErr, io.EOF) {
				return 0, "", fmt.Errorf("read replacement filename: %w", readErr)
			}
			return ActionAlternate, strings.TrimSpace(alternate), nil
		default:
			if _, err := fmt.Fprintln(output, "Choose o, s, r, or a."); err != nil {
				return 0, "", err
			}
		}
		if errors.Is(err, io.EOF) {
			return 0, "", errors.New("collision choice is required")
		}
	}
}

func nextAvailableName(dir, relativePath string) (string, error) {
	clean, err := safeRelativePath(relativePath)
	if err != nil {
		return "", err
	}
	extension := filepath.Ext(clean)
	base := strings.TrimSuffix(clean, extension)
	for number := 1; number < 10000; number++ {
		candidate := fmt.Sprintf("%s_%d%s", base, number, extension)
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(candidate))); os.IsNotExist(err) {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("could not find an available name for %s", relativePath)
}

func safeRelativePath(filePath string) (string, error) {
	clean := path.Clean(strings.TrimSpace(filePath))
	if clean == "." || clean == "" || strings.HasPrefix(clean, "/") || clean == ".." || strings.HasPrefix(clean, "../") {
		return "", fmt.Errorf("invalid scaffold filename %q", filePath)
	}
	return clean, nil
}

func isTerminal(input io.Reader) bool {
	file, ok := input.(*os.File)
	if !ok || file == nil || file != os.Stdin {
		return false
	}
	info, err := file.Stat()
	return err == nil && info.Mode()&os.ModeCharDevice != 0
}

func containsFold(values []string, needle string) bool {
	for _, value := range values {
		if strings.EqualFold(value, needle) {
			return true
		}
	}
	return false
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}
